package com.lampung.baktimarsada.core.constants

object AppConstants {
    const val ENCRYPTED_PREFS_NAME = "bakti_marsada_encrypted_prefs"

    const val KEY_FCM_TOKEN = "key_fcm_token"
    const val KEY_DB_PASSPHRASE = "key_db_passphrase"
    const val KEY_AUTH_TOKEN = "key_auth_token"
    const val KEY_USER_ID = "key_user_id"
    const val KEY_DISPLAY_NAME = "key_display_name"
    const val KEY_USER_ROLE = "key_user_role"
    const val KEY_TENANT_ID = "key_tenant_id"
    const val KEY_TENANT_NAME = "key_tenant_name"
    const val KEY_SUB_TENANT_ID = "key_sub_tenant_id"
    const val KEY_SUB_TENANT_NAME = "key_sub_tenant_name"
    const val KEY_SECTOR_ID = "key_sector_id"
    const val KEY_SECTOR_NAME = "key_sector_name"

    const val FIRESTORE_COLLECTION_TRACKING = "device_events"
    const val FIRESTORE_COLLECTION_USERS = "users"
    const val FIRESTORE_COLLECTION_EVENTS = "events"
    const val FIRESTORE_COLLECTION_MEMBERS = "members"
    const val FIRESTORE_COLLECTION_FINANCE_REPORTS = "finance_reports"
    const val FIRESTORE_COLLECTION_PAYMENT_OBLIGATIONS = "payment_obligations"
    const val FIRESTORE_FIELD_EVENT_TYPE = "event_type"
    const val FIRESTORE_FIELD_TIMESTAMP = "timestamp"
    const val FIRESTORE_FIELD_SELECTED_ROLE = "selected_role"
    const val FIRESTORE_FIELD_INTEREST_COUNT = "interest_count"
    const val FIRESTORE_FIELD_TOKEN_LENGTH = "token_length"
    const val FIRESTORE_FIELD_MESSAGE = "message"
    const val FIRESTORE_FIELD_SOURCE = "source"
    const val FIRESTORE_FIELD_HAS_DATA = "has_data"
    const val FIRESTORE_FIELD_NOTIFICATION_TITLE = "notification_title"
    const val FIRESTORE_FIELD_IDENTIFIER = "identifier"
    const val FIRESTORE_FIELD_IDENTIFIER_NORMALIZED = "identifier_normalized"
    const val FIRESTORE_FIELD_PASSWORD = "password"
    const val FIRESTORE_FIELD_USER_ID = "user_id"
    const val FIRESTORE_FIELD_DISPLAY_NAME = "display_name"
    const val FIRESTORE_FIELD_ROLE = "role"
    const val FIRESTORE_FIELD_SECTOR_ID = "sector_id"
    const val FIRESTORE_FIELD_SECTOR_NAME = "sector_name"
    const val FIRESTORE_FIELD_TITLE = "title"
    const val FIRESTORE_FIELD_DESCRIPTION = "description"
    const val FIRESTORE_FIELD_SCHEDULED_AT = "scheduled_at"
    const val FIRESTORE_FIELD_LOCATION = "location"
    const val FIRESTORE_FIELD_FULL_NAME = "full_name"
    const val FIRESTORE_FIELD_FAMILY_GROUP = "family_group"
    const val FIRESTORE_FIELD_PHONE_NUMBER = "phone_number"
    const val FIRESTORE_FIELD_ADDRESS = "address"
    const val FIRESTORE_FIELD_ROLE_IN_SECTOR = "role_in_sector"
    const val FIRESTORE_FIELD_PERIOD_LABEL = "period_label"
    const val FIRESTORE_FIELD_AMOUNT = "amount"
    const val FIRESTORE_FIELD_IS_VISIBLE_TO_JEMAAT = "is_visible_to_jemaat"
    const val FIRESTORE_FIELD_MEMBER_ID = "member_id"
    const val FIRESTORE_FIELD_MEMBER_NAME = "member_name"
    const val FIRESTORE_FIELD_DUE_DATE = "due_date"
    const val FIRESTORE_FIELD_STATUS = "status"

    const val VALUE_UNKNOWN = "unknown"
    const val VALUE_EMPTY = ""

    const val TRACKING_EVENT_TOKEN_REFRESHED = "fcm_token_refreshed"
    const val TRACKING_EVENT_MESSAGE_RECEIVED = "fcm_message_received"
    const val QUALIFIER_CLOUDFLARE_API = "cloudflare_api"
    const val QUALIFIER_PYTHON_API = "python_api"
    const val QUALIFIER_SIMULATE_SOURCE = "simulate_source"
    const val ROUTE_SYNC_FCM_TOKEN = "v1/device/fcm-token"
    const val ROUTE_AUTH_LOGIN = "auth/login"
    const val ROUTE_AUTH_LOGOUT = "auth/logout"
    const val ROUTE_EVENTS = "v1/events"
    const val ROUTE_MEMBERS = "v1/members"
    const val ROUTE_FINANCE_REPORTS = "v1/finance-reports"
    const val ROUTE_PAYMENT_OBLIGATIONS = "v1/payment-obligations"

}
